name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_FEATURE_FLAGS: manifests,dependencygraph

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
          - os: windows-latest
            triplet: x64-windows

    runs-on: ${{ matrix.os }}

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}		# Not used in ubuntu-latest
      VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.triplet }}		# Not used in ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # harmless even if you don't have submodules

      - name: Setup Build Essentials in Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build cmake tar git zip unzip curl pkg-config libboost-program-options-dev libarmadillo-dev libcereal-dev 

      - name: Install igraph 1.0.0 from source (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get remove -y libigraph-dev || true
          sudo apt-get install -y liblapack-dev libblas-dev
          curl -L https://github.com/igraph/igraph/releases/download/1.0.0/igraph-1.0.0.tar.gz -o igraph-1.0.0.tar.gz
          tar -xzf igraph-1.0.0.tar.gz
          cd igraph-1.0.0
          mkdir build && cd build
          cmake ..  -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DIGRAPH_ENABLE_R=OFF -DIGRAPH_ENABLE_PYTHON=OFF
          cmake --build . -- -j"$(nproc)"
          sudo cmake --install .
          sudo ldconfig

      - name: Install CMake (Mac & Windows)
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg (Mac & Windows)
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake (Ubuntu) 
        if: matrix.os == 'ubuntu-latest'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Configure CMake (Mac & Windows) 
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - name: Install into stage/
        run: |
          cmake --install build --config Release --prefix "${{ github.workspace }}/stage"
          echo "Installed tree:"
          find stage -maxdepth 3 -type f || true

      - name: Print Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "> ldd stage/bin/loga"
          ldd stage/bin/loga | tee stage/loga.exe.deps.txt || true
          echo "> ldd stage/lib/libloga.so"
          ldd stage/lib/libloga.so | tee stage/libloga.deps.txt || true

      - name: Print Dependencies (Mac)
        if: matrix.os == 'macos-latest'
        run: |
          echo "> otool -L stage/bin/loga"
          otool -L stage/bin/loga | tee stage/loga.exe.deps.txt || true
          echo "> otool -L stage/lib/libloga.dylib"
          otool -L stage/lib/libloga.dylib | tee stage/libloga.deps.txt || tru

      - name: Setup MSVC dev cmd
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          
      - name: Print Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          echo "> dumpbin /DEPENDENTS stage\bin\loga.exe"
          dumpbin /DEPENDENTS stage\bin\loga.exe | Tee-Object -FilePath stage\loga.exe.deps.txt
          echo "> dumpbin /DEPENDENTS stage\lib\loga.dll"
          dumpbin /DEPENDENTS stage\lib\loga.dll | Tee-Object -FilePath stage\libloga.deps.txt

      - name: Upload stage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: loga-${{ matrix.os }}-stage
          path: stage
